#!/usr/bin/env bash

upload_api_doc () {
    sbt doc && \
        now switch xieyuheng && \
        now -n cicada target/scala-2.12/api/ && \
        surge target/scala-2.12/api/ cicada.surge.sh
}

get_classpath () {
    mkdir -p target
    sbt -error "export runtime:fullClasspath" > target/classpath
}

t () {
    rm -f target/universal/stage/bin/*

    sbt stage && \
        run_test && \
        run_minitt_test && \
        run_lambda_test && \
        run_syst_test
}

run_test () {
    for file in $(find . | grep "^\./target/universal/stage/bin/" | grep "test$")
    do
        echo ""
        echo "[test] $file"
        if ! time $file
        then
            exit 1
        fi
    done
}

run_minitt_test () {
    minitt=./target/universal/stage/bin/minitt

    for file in $(find . | grep "^\./example/minitt/" | grep "\.minitt$")
    do
        echo ""
        echo "[minitt_test] $file"
        if ! time $minitt --eval $file
        then
            exit 1
        fi
    done
}

run_lambda_test () {
    lambda=./target/universal/stage/bin/lambda

    for file in $(find . | grep "^\./example/lambda/" | grep "\.lambda$")
    do
        echo ""
        echo "[lambda_test] $file"
        if ! time $lambda --eval $file
        then
            exit 1
        fi
    done
}

run_syst_test () {
    syst=./target/universal/stage/bin/syst

    for file in $(find . | grep "^\./example/syst/" | grep "\.syst$")
    do
        echo ""
        echo "[syst_test] $file"
        if ! time $syst --eval $file
        then
            exit 1
        fi
    done
}

build_minitt () {
    mkdir -p target/linux/bin/
    get_classpath

    native-image \
        --no-server \
        -cp $(cat target/classpath) \
        -H:Name="target/linux/bin/minitt" \
        -H:Class="xieyuheng.minitt.minitt"
}

build_lambda () {
    mkdir -p target/linux/bin/
    get_classpath

    native-image \
        --no-server \
        -cp $(cat target/classpath) \
        -H:Name="target/linux/bin/lambda" \
        -H:Class="xieyuheng.lambda.lambda"
}

build_syst () {
    mkdir -p target/linux/bin/
    get_classpath

    native-image \
        --no-server \
        -cp $(cat target/classpath) \
        -H:Name="target/linux/bin/syst" \
        -H:Class="xieyuheng.syst.syst"
}

release () {
    cp -r target/linux/ ~/proj/cicada-release/ && \
        pushd ~/proj/cicada-release/ && \
        git add . && \
        git commit -m "up" && \
        git push && \
        popd
}

main () {
    for TASK in $@
    do
        $TASK
    done
}

main $@
